title: ML4Materials
description: Machine Learning for Clean Energy Research
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-default-layout

url: https://uwsunlab.github.io/ML4Materials

