title: ML4Materials
description: Machine Learning for Clean Energy Research
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-default-layout

url: https://uwsunlab.github.io/ML4Materials

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/just-the-docs.png"

